---
- name: Install and configure Apache Tomcat
  hosts: tomcat-server
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - openjdk-11-jdk
          - curl
          - unzip
        state: present

    - name: Create Tomcat group
      group:
        name: tomcat
        state: present

    - name: Create Tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/false
        home: /opt/tomcat
        create_home: no
        system: yes

    - name: Download Apache Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.98/bin/apache-tomcat-9.0.98.tar.gz
        dest: /tmp/apache-tomcat-9.0.98.tar.gz

    - name: Extract Tomcat archive
      unarchive:
        src: /tmp/apache-tomcat-9.0.98.tar.gz
        dest: /opt
        remote_src: yes    #This actually tells Ansible that the Archive is on the remote host

    - name: Set Tomcat directory permissions
      file:
        path: /opt/apache-tomcat-9.0.98
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Create symbolic link for Tomcat
      file:
        src: /opt/apache-tomcat-9.0.98
        dest: /opt/tomcat
        state: link

    - name: Start Tomcat service
      shell: /opt/tomcat/bin/startup.sh
